### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-piholeOFF - Not found

### ISSUE THREAD

**Issue by Nastras** [thkl/homebridge-piholeOff#1]
Hello

i was just about to try your plugin, unfortunately it does not install over nem. I get the following error message:

`nastras@SHS:~ $ sudo npm install -g --unsafe-perm homebridge-piholeOFF@latest -g
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-piholeOFF - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-piholeOFF@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`

Then I have another question for you. What exactly is URL function for. Can you explain it briefly?

Thanks a lot for your help.

Best regards
Nastras

**Comment by arendruni** [comment]
Have you tried writing the name of the plugin lowercase? `sudo npm install -g --unsafe-perm homebridge-piholeoff@latest`

**Comment by Nastras** [comment]
Hey @arendruni, you could have thought of that yourself 😅
Now the installation has worked 👍

Thanks for the tip.

I have opened an issue this morning at your plugin would be nice if you could tell me if you put it in your plugin and I wouldn't change it?
